### PR TITLE
Fix get_curve_{publickey,secretkey,serverkey} (rebased)

### LINKED ISSUE #85: `Zmq.Socket.get_curve_publickey` fails with EINVAL
Here is the stacktrace:

```
Unix.Unix_error(Unix.EINVAL, "zmq_getsockopt", "")
Raised by primitive operation at file "zmq/src/zmq.ml", line 455, characters 4-47
```

The reason is pretty simple: for the curve related option, libzmq uses the size of the return buffer to choose between returning the raw key (if the buffer length is 32 or the z85 encoded version if it's 40+1 (+1 for some reason). Have a look at `do_getsockopt_curve_key` in `options.cpp`.

I'm about to send a PR that sets the return buffer length explicitly to 41 so we get back nice z85 keys. Other approaches are of course possible, such as adding an option for the user to choose, but I think it's more convenient to have only one format everywhere (given conversion functions between the two formats are available anyway).

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
For those, the size of the buffer passed to getsockopt is significant and must be either 32 (to receive key as binary) or 41 (to receive key as z85).

The patch merely sets the buffer size to 41 for those options, so that the caller is returned the keys in z85 format.

Previously, calling those functions would result in an error with errno set to EINVAL.

Closes #85
Closes #86

(Rebased from the previous PR #86 by @rixed which we partly merged, so we can see it build on CI)

### CODE REVIEW

File: zmq/src/caml_zmq_stubs.c [hunk 1]
```diff
@@ -304,10 +305,11 @@ CAMLprim value caml_zmq_get_int64_option(value socket, value option_name) {
...
 }
 
-CAMLprim value caml_zmq_get_bytes_option(value socket, value option_name) {
-    CAMLparam2 (socket, option_name);
+CAMLprim value caml_zmq_get_bytes_option(value socket, value option_name, value option_maxlen) {
+    CAMLparam3 (socket, option_name, option_maxlen);
     char buffer[256];
-    size_t buffer_size = sizeof (buffer) - 1;
+    size_t buffer_size = Unsigned_long_val(option_maxlen);
+    assert(buffer_size <= sizeof (buffer));
```
Comment (andersfugmann) [inline zmq/src/caml_zmq_stubs.c]: We should just copy the data returned from the zmq call, and not use `caml_copy_string`. Also there is an write pas end problem when adding the \0.

File: zmq/src/zmq.ml [hunk 2]
```diff
@@ -232,8 +232,11 @@ module Socket = struct
     validate_string_length 1 255 identity "set_identity";
     set_bytes_option socket ZMQ_IDENTITY identity
 
+  let maximal_buffer_length = 256
```
Comment (andersfugmann) [inline zmq/src/zmq.ml]: If we keep the buffer size in the c-stub at 256 bytes and want to rtie `\0` at the end of the buffer, this value should be lowered by one.
